### ISSUE TITLE
Susceptible to Man-in-the-Middle

### ISSUE THREAD

**Issue by rriley** [TorGuard/openwrt-scripts#4]
Hi,

I notice that the scripts here disable certificate validation when connecting to the API.  (`--no-check-certificate` on `wget` or `-k` on `curl`).  This makes that API connection susceptible to a man-in-the-middle attack, which a crafty attacker could then leverage to perform a MitM attack on the VPN connection itself.

This can be fixed by just validating the certificate.

For `wget`, for example, it should be...
`wget --ca-certificate=ca.crt`

For `curl`, it should be...
`curl --cacert ca.crt`

Where `ca.cert` contains...
```
-----BEGIN CERTIFICATE-----
MIIEujCCAqKgAwIBAgIRAOLkx9DgmetClFsZ11C9TDIwDQYJKoZIhvcNAQENBQAw
PTERMA8GA1UECgwIVG9yR3VhcmQxKDAmBgNVBAMMH1Rvckd1YXJkIFByaXZhdGUg
Um9vdCBDQSAxIDIwMjAwHhcNMjAwODA1MTk1MjUzWhcNMjQwODA0MTk1MjUzWjA0
MREwDwYDVQQKDAhUb3JHdWFyZDEfMB0GA1UEAwwWVG9yR3VhcmQgVlBOIFNlcnZl
ciBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKcu3+XcrvJIzhxw
GOnkbn1hA4gjpe9qp0HU2gkaciUG7MyBgulfGAJh2ZhRUtVN2r6ZSdGP/nXTcYmj
6dQLo1ohruTkbgbbwRAynFJQQaFidO6eD1o7snFNMaBwiNNLjK7jlMgjHAPpmMcl
+0adW0xPRalTWlI07Fwl7VO8D7yJtmS1v1Ip8SjutnEw8ynrZIJeldqJTgGrqevk
FWy7f1MhXlnNmNG7edp18hE6fKrRVSN8QmcZ9KgcSsZ9i4MwSeiXV1feGPNfFQxA
DwA652r0TsRNjPUd1bDEad1f8Mb8X5QvSXrCkNn8n1DJK9zOqKaLhztt1ICr9WHQ
QQPXRIkCAwEAAaOBvTCBujAOBgNVHQ8BAf8EBAMCAsQwEgYDVR0TAQH/BAgwBgEB
/wIBADAdBgNVHQ4EFgQUXEcNR/LSidNqZyw5qrXZnWxZsXIwdQYDVR0jBG4wbIAU
r7BhTzn5fCHgXDiUT2Yl86Fm372hQaQ/MD0xETAPBgNVBAoMCFRvckd1YXJkMSgw
JgYDVQQDDB9Ub3JHdWFyZCBQcml2YXRlIFJvb3QgQ0EgMSAyMDIwghEA4uTH0OCZ
60KUWxnXUL1MMDANBgkqhkiG9w0BAQ0FAAOCAgEAFL9QVr1qWVrtctoiq/fI865y
4hb7T5rhWiCGeGh0qqkXX3hOtY0jPD4afjAwbP5rDkxujs08ZRm2RbwfjSBSkFgS
7rFYB88wcmJqVbAzy0vKtMougY/hxZZGqXcL0pAQJuJQVIQlLo1siiVfWk4jb9ue
X/o4zjXnoqGgiziQ/pXd9sgSnWZ9u8obszbNu15Nb/9HYie9ZezB+1VYNkIiCazk
E7zeahcfX/Epje5VX7Am7romcjXpX3zwozD5kEASo7YC0FZsJx1KH5/R4vpSwSB6
QwditKGqS7giA5191lmpeHCxxLH0w4KOAlbnkpHUWWhovDqxxupi4RoxALSTD/c5
ueEck+zjDFLHM11/A7c29UczyOBaVXNmsf969jRgKodTY/gejIW8WH6OnjYpYZhn
5h70Jr0xt8rppo7BqX9UUJbIKIfqHRTBuy9MHIamkYks1SY85TyrfSsSQOSg6AlS
aM92o+jm3qoVza75Ksa8Wel3pgs6FUfAp8aPRaQ+ysYV2Qlp6Byd702VuzdIfc/1
BlMk6TYfMFiaESBensO5GTa6p8ZEXOOsN3OSRc51iZ5OEMRp1w6364JnYNK9vmdA
OJdOz5njXFgb1BetQVuMY06pT861ByCQ0tl5XZycQf2ifFoAlZSwWkP5DFV5Ozq2
dI1mOMT8mRwIDfOfBJc=
-----END CERTIFICATE-----
```

I hope this is helpful.

**Comment by TorGuard** [comment]
@rriley thanks for nice and short explanation as well as resolution suggestion, also, I am sorry to reply that late, I simply oversaw the issue and read the email today.

Those scripts were written so to say on the fly with a tough that a normal Joe can read/use them, but I admit it is a wrong though by me, as normal Joe of commercial product does not even want to read, rather just to click on connect, some might maybe argue on that. Also, scripts should be also refactored as well as audited, I hoped it will happen by users, just like you did. Together with changes which happened on TorGuard, as TorGuard was still in "testing" phase of API, there were indeed not many who actually would like to analyze it deeply.

The api itself should have not been part of current scripts, I agree that whole design is probably not optimal and expressed it, TorGuard also replied that no further api validation will be required due to the fact that they will remove the timeout. When I first wrote those scripts, timeout was about 1 hour, then it was reduced to 15 minutes and some time later even 15 minutes seems to have been reduced where from my observation, running API fix every lets say 14 minutes did not fix it, but running it every minute did, which was at some point confusing to me.

What I dislike even more is a need to use username and password instead of as example hashes, but to be honest, I did not test it further because I asked torguard for some specification of their api which I did not receive until now. For additional layer of security, maybe 2fa could be added (at least for TorGuard app when connecting/launching app) but I would not be a fan of automatic 2fa usage as it offers then no more security if script on its own already knows credentials as well as the seed and its settings, it eradicates then second authentification. On that point, if attacker or any sniffer gets credentials, then those can be used without any limitation, seeing open ports and everything else which one could imagine.

Those scripts were also actually a primitive reproduction of what torguard application does, where in fact, TorGuard app suffers from same issue of using credentials instead of some more sophisticated methods.

For the certificate part, I indeed tested it back the with certificate which worked as you suggest, main reason was me believing that api restriction is just temporal and will change which indeed later changed. Second reason were users who might find it even more complicated/discouraging if I include some certificates here. I am also currently a little confused about it, especially as there is a statement from torguard support that expiration is disabled, but it is not, some still expire and the only working way is still to use the API. Therefore, thank you very much for pointing this out, your are 100% right in your observation and I will change scripts to your proposal. Also, thank you for using github and place it here as issue, thanks for using your free time to help me/other users out, much appreciated.
